<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace lib\util;

use \php\Boot;

class ListUtil {
	/**
	 * @param \Array_hx $list
	 * @param int $i
	 * 
	 * @return string
	 */
	public static function Get ($list, $i) {
		#src/lib/util/ListUtil.hx:14: lines 14-17
		if (ListUtil::IsValidIndex($list, $i)) {
			#src/lib/util/ListUtil.hx:16: characters 13-27
			return ($list->arr[$i] ?? null);
		}
		#src/lib/util/ListUtil.hx:18: characters 9-20
		return null;
	}

	/**
	 * @param \Array_hx $list
	 * @param int $index
	 * 
	 * @return bool
	 */
	public static function IsValidIndex ($list, $index) {
		#src/lib/util/ListUtil.hx:10: characters 16-65
		if (($list !== null) && ($index >= 0)) {
			#src/lib/util/ListUtil.hx:10: characters 46-65
			return $index < $list->length;
		} else {
			#src/lib/util/ListUtil.hx:10: characters 16-65
			return false;
		}
	}

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(ListUtil::class, 'lib.util.ListUtil');
