<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace lib\util;

use \system\text\Encoding;
use \php\Boot;
use \psgg\HxFile;
use \php\_Boot\HxString;

class PsggDataFileUtil {
	/**
	 * @param string $path
	 * 
	 * @return PsggDataFileUtil_Item
	 */
	public static function ReadPsgg ($path) {
		#src/lib/util/PsggDataFileUtil.hx:10: characters 9-99
		$buf = HxFile::ReadAllText_String_Encoding($path, Encoding::get_UTF8());
		#src/lib/util/PsggDataFileUtil.hx:11: characters 9-33
		return PsggDataFileUtil::ReadPsggData($buf);
	}

	/**
	 * @param string $data
	 * 
	 * @return PsggDataFileUtil_Item
	 */
	public static function ReadPsggData ($data) {
		#src/lib/util/PsggDataFileUtil.hx:15: characters 9-88
		$item = new PsggDataFileUtil_Item();
		#src/lib/util/PsggDataFileUtil.hx:16: characters 9-31
		$buf = $data;
		#src/lib/util/PsggDataFileUtil.hx:17: characters 9-54
		$list = new \Array_hx();
		#src/lib/util/PsggDataFileUtil.hx:18: lines 18-28
		while (($buf !== null) && (mb_strlen($buf) > 1)) {
			#src/lib/util/PsggDataFileUtil.hx:20: characters 13-83
			$index = HxString::indexOf($buf, "------#======*<Guid(", 1);
			#src/lib/util/PsggDataFileUtil.hx:21: lines 21-24
			if ($index < 0) {
				#src/lib/util/PsggDataFileUtil.hx:23: characters 17-22
				break;
			}
			#src/lib/util/PsggDataFileUtil.hx:25: characters 13-52
			$pick = \mb_substr($buf, 0, $index);
			#src/lib/util/PsggDataFileUtil.hx:26: characters 13-28
			$list->arr[$list->length++] = $pick;
			#src/lib/util/PsggDataFileUtil.hx:27: characters 19-36
			$buf = \mb_substr($buf, $index, null);
		}
		#src/lib/util/PsggDataFileUtil.hx:29: lines 29-32
		if (($buf !== null) && (mb_strlen($buf) > 0)) {
			#src/lib/util/PsggDataFileUtil.hx:31: characters 13-27
			$list->arr[$list->length++] = $buf;
		}
		#src/lib/util/PsggDataFileUtil.hx:33: characters 9-23
		$i = 0;
		#src/lib/util/PsggDataFileUtil.hx:34: lines 34-76
		$_g = 0;
		while ($_g < $list->length) {
			#src/lib/util/PsggDataFileUtil.hx:34: characters 14-22
			$listitem = ($list->arr[$_g] ?? null);
			#src/lib/util/PsggDataFileUtil.hx:34: lines 34-76
			++$_g;
			#src/lib/util/PsggDataFileUtil.hx:36: lines 36-74
			if ($i === 0) {
				#src/lib/util/PsggDataFileUtil.hx:38: characters 17-45
				$item->m_header_buf = $listitem;
			} else if (HxString::indexOf($listitem, "------#======*<Guid(D13821FE-FA27-4B04-834C-CEC1E5670F48)>*======#------") >= 0) {
				#src/lib/util/PsggDataFileUtil.hx:42: characters 17-44
				$item->m_chart_buf = $listitem;
			} else if (HxString::indexOf($listitem, "------#======*<Guid(70C5A739-223A-457D-8AEE-1A0E2050D5AE)>*======#------") >= 0) {
				#src/lib/util/PsggDataFileUtil.hx:46: lines 46-69
				if (HxString::indexOf($listitem, "sheet=config") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:48: characters 21-49
					$item->m_config_buf = $listitem;
				} else if (HxString::indexOf($listitem, "sheet=template-source") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:52: characters 21-49
					$item->m_tmpsrc_buf = $listitem;
				} else if (HxString::indexOf($listitem, "sheet=template-statefunc") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:56: characters 21-49
					$item->m_tmpfnc_buf = $listitem;
				} else if (HxString::indexOf($listitem, "sheet=setting.ini") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:60: characters 21-50
					$item->m_setting_buf = $listitem;
				} else if (HxString::indexOf($listitem, "sheet=help") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:64: characters 21-47
					$item->m_help_buf = $listitem;
				} else if (HxString::indexOf($listitem, "sheet=itemsinfo") >= 0) {
					#src/lib/util/PsggDataFileUtil.hx:68: characters 21-50
					$item->m_iteminf_buf = $listitem;
				}
			} else if (HxString::indexOf($listitem, "------#======*<Guid(4DC98CBA-6257-4E26-A454-A53F85BC234C)>*======#------") >= 0) {
				#src/lib/util/PsggDataFileUtil.hx:73: characters 17-45
				$item->m_bitmap_buf = $listitem;
			}
			#src/lib/util/PsggDataFileUtil.hx:75: characters 13-16
			++$i;
		}
		#src/lib/util/PsggDataFileUtil.hx:77: lines 77-94
		$get_tmp = function ($s) {
			#src/lib/util/PsggDataFileUtil.hx:79: characters 13-77
			$begin = "###VARIOUS-CONTENTS-BEGIN###";
			#src/lib/util/PsggDataFileUtil.hx:80: characters 13-73
			$end = "###VARIOUS-CONTENTS-END###";
			#src/lib/util/PsggDataFileUtil.hx:81: characters 13-43
			$si = HxString::indexOf($s, $begin);
			#src/lib/util/PsggDataFileUtil.hx:82: lines 82-85
			if ($si < 0) {
				#src/lib/util/PsggDataFileUtil.hx:84: characters 17-28
				return null;
			}
			#src/lib/util/PsggDataFileUtil.hx:86: characters 13-57
			$s1 = \mb_substr($s, $si + mb_strlen($begin), null);
			#src/lib/util/PsggDataFileUtil.hx:87: characters 13-42
			$ei = HxString::indexOf($s1, $end);
			#src/lib/util/PsggDataFileUtil.hx:88: lines 88-91
			if ($ei < 0) {
				#src/lib/util/PsggDataFileUtil.hx:90: characters 17-28
				return null;
			}
			#src/lib/util/PsggDataFileUtil.hx:92: characters 13-36
			return \mb_substr($s1, 0, $ei);
		};
		#src/lib/util/PsggDataFileUtil.hx:95: characters 9-51
		$item->m_tmpsrc = $get_tmp($item->m_tmpsrc_buf);
		#src/lib/util/PsggDataFileUtil.hx:96: characters 9-51
		$item->m_tmpfnc = $get_tmp($item->m_tmpfnc_buf);
		#src/lib/util/PsggDataFileUtil.hx:97: characters 9-20
		return $item;
	}

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(PsggDataFileUtil::class, 'lib.util.PsggDataFileUtil');
