<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace haxe\ds;

use \php\Boot;
use \haxe\IMap;

/**
 * BalancedTree allows key-value mapping with arbitrary keys, as long as they
 * can be ordered. By default, `Reflect.compare` is used in the `compare`
 * method, which can be overridden in subclasses.
 * Operations have a logarithmic average and worst-case cost.
 * Iteration over keys and values, using `keys` and `iterator` respectively,
 * are in-order.
 */
class BalancedTree implements IMap {
	/**
	 * @var TreeNode
	 */
	public $root;

	/**
	 * Creates a new BalancedTree, which is initially empty.
	 * 
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @param TreeNode $l
	 * @param mixed $k
	 * @param mixed $v
	 * @param TreeNode $r
	 * 
	 * @return TreeNode
	 */
	public function balance ($l, $k, $v, $r) {
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:206: characters 3-27
		$hl = ($l === null ? 0 : $l->_height);
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:207: characters 3-27
		$hr = ($r === null ? 0 : $r->_height);
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:208: lines 208-222
		if ($hl > ($hr + 2)) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:209: characters 8-27
			$_this = $l->left;
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:209: characters 31-51
			$_this1 = $l->right;
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:209: lines 209-213
			if ((($_this === null ? 0 : $_this->_height)) >= (($_this1 === null ? 0 : $_this1->_height))) {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:210: characters 24-30
				$l1 = $l->left;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:210: characters 32-37
				$l2 = $l->key;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:210: characters 39-46
				$l3 = $l->value;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:210: characters 5-85
				return new TreeNode($l1, $l2, $l3, new TreeNode($l->right, $k, $v, $r));
			} else {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:212: characters 24-80
				$tmp = new TreeNode($l->left, $l->key, $l->value, $l->right->left);
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:212: characters 82-93
				$l1 = $l->right->key;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:212: characters 95-108
				$l2 = $l->right->value;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:212: lines 212-213
				return new TreeNode($tmp, $l1, $l2, new TreeNode($l->right->right, $k, $v, $r));
			}
		} else if ($hr > ($hl + 2)) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:215: characters 8-28
			$_this = $r->right;
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:215: characters 31-50
			$_this1 = $r->left;
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:215: lines 215-219
			if ((($_this === null ? 0 : $_this->_height)) > (($_this1 === null ? 0 : $_this1->_height))) {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:216: characters 5-85
				return new TreeNode(new TreeNode($l, $k, $v, $r->left), $r->key, $r->value, $r->right);
			} else {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:218: characters 24-64
				$tmp = new TreeNode($l, $k, $v, $r->left->left);
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:218: characters 66-76
				$r1 = $r->left->key;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:218: characters 78-90
				$r2 = $r->left->value;
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:218: lines 218-219
				return new TreeNode($tmp, $r1, $r2, new TreeNode($r->left->right, $r->key, $r->value, $r->right));
			}
		} else {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:221: characters 4-59
			return new TreeNode($l, $k, $v, $r, (($hl > $hr ? $hl : $hr)) + 1);
		}
	}

	/**
	 * @param mixed $k1
	 * @param mixed $k2
	 * 
	 * @return int
	 */
	public function compare ($k1, $k2) {
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:226: characters 3-33
		return \Reflect::compare($k1, $k2);
	}

	/**
	 * Returns the value `key` is bound to.
	 * If `key` is not bound to any value, `null` is returned.
	 * If `key` is null, the result is unspecified.
	 * 
	 * @param mixed $key
	 * 
	 * @return mixed
	 */
	public function get ($key) {
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:62: characters 3-19
		$node = $this->root;
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:63: lines 63-71
		while ($node !== null) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:64: characters 4-35
			$c = $this->compare($key, $node->key);
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:65: lines 65-66
			if ($c === 0) {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:66: characters 5-22
				return $node->value;
			}
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:67: lines 67-70
			if ($c < 0) {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:68: characters 5-21
				$node = $node->left;
			} else {
				#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:70: characters 5-22
				$node = $node->right;
			}
		}
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:72: characters 3-14
		return null;
	}

	/**
	 * Binds `key` to `value`.
	 * If `key` is already bound to a value, that binding disappears.
	 * If `key` is null, the result is unspecified.
	 * 
	 * @param mixed $key
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function set ($key, $value) {
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:51: characters 3-35
		$this->root = $this->setLoop($key, $value, $this->root);
	}

	/**
	 * @param mixed $k
	 * @param mixed $v
	 * @param TreeNode $node
	 * 
	 * @return TreeNode
	 */
	public function setLoop ($k, $v, $node) {
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:151: lines 151-152
		if ($node === null) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:152: characters 4-47
			return new TreeNode(null, $k, $v, null);
		}
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:153: characters 3-32
		$c = $this->compare($k, $node->key);
		#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:154: lines 154-160
		if ($c === 0) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:154: characters 22-88
			return new TreeNode($node->left, $k, $v, $node->right, ($node === null ? 0 : $node->_height));
		} else if ($c < 0) {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:155: characters 4-38
			$nl = $this->setLoop($k, $v, $node->left);
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:156: characters 4-49
			return $this->balance($nl, $node->key, $node->value, $node->right);
		} else {
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:158: characters 4-39
			$nr = $this->setLoop($k, $v, $node->right);
			#G:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:159: characters 4-48
			return $this->balance($node->left, $node->key, $node->value, $nr);
		}
	}
}

Boot::registerClass(BalancedTree::class, 'haxe.ds.BalancedTree');
