<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace haxe;

use \php\Boot;

class MainLoop {
	/**
	 * @var MainEvent
	 */
	static public $pending;

	/**
	 * @return bool
	 */
	public static function hasEvents () {
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:67: characters 3-19
		$p = MainLoop::$pending;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:68: lines 68-72
		while ($p !== null) {
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:69: lines 69-70
			if ($p->isBlocking) {
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:70: characters 5-16
				return true;
			}
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:71: characters 4-14
			$p = $p->next;
		}
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:73: characters 3-15
		return false;
	}

	/**
	 * @return void
	 */
	public static function sortEvents () {
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:103: characters 3-22
		$list = MainLoop::$pending;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:105: lines 105-106
		if ($list === null) {
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:106: characters 4-10
			return;
		}
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:108: characters 3-49
		$insize = 1;
		$nmerges = null;
		$psize = 0;
		$qsize = 0;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:109: characters 3-31
		$p = null;
		$q = null;
		$e = null;
		$tail = null;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:111: lines 111-156
		while (true) {
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:112: characters 4-12
			$p = $list;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:113: characters 4-15
			$list = null;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:114: characters 4-15
			$tail = null;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:115: characters 4-15
			$nmerges = 0;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:116: lines 116-151
			while ($p !== null) {
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:117: characters 5-14
				++$nmerges;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:118: characters 5-10
				$q = $p;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:119: characters 5-14
				$psize = 0;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:120: characters 15-19
				$_g = 0;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:120: characters 19-25
				$_g1 = $insize;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:120: lines 120-125
				while ($_g < $_g1) {
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:120: characters 15-25
					$i = $_g++;
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:121: characters 6-13
					++$psize;
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:122: characters 6-16
					$q = $q->next;
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:123: lines 123-124
					if ($q === null) {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:124: characters 7-12
						break;
					}
				}
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:126: characters 5-19
				$qsize = $insize;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:127: lines 127-149
				while (($psize > 0) || (($qsize > 0) && ($q !== null))) {
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:128: lines 128-142
					if ($psize === 0) {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:129: characters 7-12
						$e = $q;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:130: characters 7-17
						$q = $q->next;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:131: characters 7-14
						--$qsize;
					} else if (($qsize === 0) || ($q === null) || (($p->priority > $q->priority) || (($p->priority === $q->priority) && ($p->nextRun <= $q->nextRun)))) {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:135: characters 7-12
						$e = $p;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:136: characters 7-17
						$p = $p->next;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:137: characters 7-14
						--$psize;
					} else {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:139: characters 7-12
						$e = $q;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:140: characters 7-17
						$q = $q->next;
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:141: characters 7-14
						--$qsize;
					}
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:143: lines 143-146
					if ($tail !== null) {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:144: characters 7-20
						$tail->next = $e;
					} else {
						#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:146: characters 7-15
						$list = $e;
					}
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:147: characters 6-19
					$e->prev = $tail;
					#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:148: characters 6-14
					$tail = $e;
				}
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:150: characters 5-10
				$p = $q;
			}
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:152: characters 4-20
			$tail->next = null;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:153: lines 153-154
			if ($nmerges <= 1) {
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:154: characters 5-10
				break;
			}
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:155: characters 4-15
			$insize *= 2;
		}
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:157: characters 3-19
		$list->prev = null;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:158: characters 3-17
		MainLoop::$pending = $list;
	}

	/**
	 * Run the pending events. Return the time for next event.
	 * 
	 * @return float
	 */
	public static function tick () {
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:165: characters 3-15
		MainLoop::sortEvents();
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:166: characters 3-19
		$e = MainLoop::$pending;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:167: characters 3-32
		$now = \microtime(true);
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:168: characters 3-18
		$wait = 1e9;
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:169: lines 169-178
		while ($e !== null) {
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:170: characters 4-22
			$next = $e->next;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:171: characters 4-29
			$wt = $e->nextRun - $now;
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:172: lines 172-176
			if ($wt <= 0) {
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:173: characters 5-13
				$wait = 0;
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:174: characters 5-13
				if ($e->f !== null) {
					($e->f)();
				}
			} else if ($wait > $wt) {
				#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:176: characters 5-14
				$wait = $wt;
			}
			#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:177: characters 4-12
			$e = $next;
		}
		#G:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:179: characters 3-14
		return $wait;
	}
}

Boot::registerClass(MainLoop::class, 'haxe.MainLoop');
