<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system\collections\generic;

use \php\Boot;

interface IComparer {
	/**
	 * @param mixed $a
	 * @param mixed $b
	 * 
	 * @return int
	 */
	public function Compare ($a, $b) ;
}

Boot::registerClass(IComparer::class, 'system.collections.generic.IComparer');
