<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system\collections\generic;

use \php\Boot;

interface IEnumerable {
	/**
	 * @return \Array_hx
	 */
	public function GetEnumerator () ;
}

Boot::registerClass(IEnumerable::class, 'system.collections.generic.IEnumerable');
