<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace lib;

use \php\Boot;

class RefListString {
	/**
	 * @var \Array_hx
	 */
	public $list;

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(RefListString::class, 'lib.RefListString');
