<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace php\_Boot;

use \php\Boot;
use \haxe\Exception;

/**
 * Closures implementation
 */
class HxClosure {
	/**
	 * @var mixed
	 * A callable value, which can be invoked by PHP
	 */
	public $callable;
	/**
	 * @var string
	 * Method name for methods
	 */
	public $func;
	/**
	 * @var mixed
	 * `this` for instance methods; php class name for static methods
	 */
	public $target;

	/**
	 * @param mixed $target
	 * @param string $func
	 * 
	 * @return void
	 */
	public function __construct ($target, $func) {
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:977: characters 3-23
		$this->target = $target;
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:978: characters 3-19
		$this->func = $func;
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:980: lines 980-982
		if (\is_null($target)) {
			#G:\HaxeToolkit\haxe\std/php/Boot.hx:981: characters 4-9
			throw Exception::thrown("Unable to create closure on `null`");
		}
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:983: characters 3-104
		$this->callable = (($target instanceof HxAnon) ? $target->{$func} : [$target, $func]);
	}

	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:991: characters 3-71
		return \call_user_func_array($this->callable, \func_get_args());
	}

	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:1018: characters 3-65
		return \call_user_func_array($this->getCallback($newThis), $args);
	}

	/**
	 * Check if this is the same closure
	 * 
	 * @param HxClosure $closure
	 * 
	 * @return bool
	 */
	public function equals ($closure) {
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:1011: characters 10-60
		if (Boot::equal($this->target, $closure->target)) {
			#G:\HaxeToolkit\haxe\std/php/Boot.hx:1011: characters 39-59
			return $this->func === $closure->func;
		} else {
			#G:\HaxeToolkit\haxe\std/php/Boot.hx:1011: characters 10-60
			return false;
		}
	}

	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:998: lines 998-1000
		if ($eThis === null) {
			#G:\HaxeToolkit\haxe\std/php/Boot.hx:999: characters 4-18
			$eThis = $this->target;
		}
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:1001: lines 1001-1003
		if (($eThis instanceof HxAnon)) {
			#G:\HaxeToolkit\haxe\std/php/Boot.hx:1002: characters 4-36
			return $eThis->{$this->func};
		}
		#G:\HaxeToolkit\haxe\std/php/Boot.hx:1004: characters 3-39
		return [$eThis, $this->func];
	}
}

Boot::registerClass(HxClosure::class, 'php._Boot.HxClosure');
