<?php
/**
 * Generated by Haxe 4.1.3
 */

use \php\Boot;
use \system\TimeSpan;

class VConstructors {
	/**
	 * @return void
	 */
	public static function init () {
		#src/VConstructors.hx:38: characters 9-25
		TimeSpan::cctor();
	}
}

Boot::registerClass(VConstructors::class, 'VConstructors');
