<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace haxe\io;

use \php\Boot;
use \haxe\Exception;

/**
 * An Output is an abstract write. A specific output implementation will only
 * have to override the `writeByte` and maybe the `write`, `flush` and `close`
 * methods. See `File.write` and `String.write` for two ways of creating an
 * Output.
 */
class Output {
	/**
	 * Close the output.
	 * Behaviour while writing after calling this method is unspecified.
	 * 
	 * @return void
	 */
	public function close () {
	}

	/**
	 * Write all bytes stored in `s`.
	 * 
	 * @param Bytes $s
	 * 
	 * @return void
	 */
	public function write ($s) {
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:104: characters 3-20
		$l = $s->length;
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:105: characters 3-13
		$p = 0;
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:106: lines 106-112
		while ($l > 0) {
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:107: characters 4-32
			$k = $this->writeBytes($s, $p, $l);
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:108: lines 108-109
			if ($k === 0) {
				#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:109: characters 5-10
				throw Exception::thrown(Error::Blocked());
			}
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:110: characters 4-10
			$p += $k;
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:111: characters 4-10
			$l -= $k;
		}
	}

	/**
	 * Write one byte.
	 * 
	 * @param int $c
	 * 
	 * @return void
	 */
	public function writeByte ($c) {
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:47: characters 3-8
		throw Exception::thrown("Not implemented");
	}

	/**
	 * Write `len` bytes from `s` starting by position specified by `pos`.
	 * Returns the actual length of written data that can differ from `len`.
	 * See `writeFullBytes` that tries to write the exact amount of specified bytes.
	 * 
	 * @param Bytes $s
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return int
	 */
	public function writeBytes ($s, $pos, $len) {
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:59: lines 59-60
		if (($pos < 0) || ($len < 0) || (($pos + $len) > $s->length)) {
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:60: characters 4-9
			throw Exception::thrown(Error::OutsideBounds());
		}
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:62: characters 3-61
		$b = $s->b;
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:63: characters 3-15
		$k = $len;
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:64: lines 64-78
		while ($k > 0) {
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:68: characters 4-25
			$this->writeByte(\ord($b->s[$pos]));
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:76: characters 4-9
			++$pos;
			#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:77: characters 4-7
			--$k;
		}
		#G:\HaxeToolkit\haxe\std/haxe/io/Output.hx:79: characters 3-13
		return $len;
	}
}

Boot::registerClass(Output::class, 'haxe.io.Output');
