<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system\text;

use \php\Boot;

class Encoding {

	/**
	 * @return UTF8Encoding
	 */
	public static function get_UTF8 () {
		#src/system/text/Encoding.hx:14: characters 3-28
		return new UTF8Encoding();
	}

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(Encoding::class, 'system.text.Encoding');
Boot::registerGetters('system\\text\\Encoding', [
	'UTF8' => true
]);
