<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system;

use \php\Boot;

class Exception {
	/**
	 * @var Exception
	 */
	public $InnerException;
	/**
	 * @var string
	 */
	public $Message;
	/**
	 * @var string
	 */
	public $StackTrace;

	/**
	 * @param string $msg
	 * @param Exception $innerException
	 * 
	 * @return void
	 */
	public function __construct ($msg = "No message", $innerException = null) {
		#src/system/Exception.hx:15: lines 15-22
		if ($msg === null) {
			$msg = "No message";
		}
		#src/system/Exception.hx:19: characters 3-21
		$this->Message = $msg;
		#src/system/Exception.hx:21: characters 3-39
		$this->InnerException = $innerException;
	}

	/**
	 * @return string
	 */
	public function toString () {
		#src/system/Exception.hx:29: characters 3-33
		return "Exception: " . ($this->Message??'null');
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(Exception::class, 'system.Exception');
