<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\Log;
use \haxe\Exception as HaxeException;

class SystemException {
	/**
	 * @var string
	 */
	public $Message;

	/**
	 * @param string $s
	 * 
	 * @return void
	 */
	public function __construct ($s) {
		#src/system/SystemException.hx:7: characters 9-14
		(Log::$trace)($s, new HxAnon([
			"fileName" => "src/system/SystemException.hx",
			"lineNumber" => 7,
			"className" => "system.SystemException",
			"methodName" => "new",
		]));
		#src/system/SystemException.hx:8: characters 9-14
		throw HaxeException::thrown($s);
	}
}

Boot::registerClass(SystemException::class, 'system.SystemException');
