<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace system;

use \php\Boot;
use \php\_Boot\HxString;

class TypeCS {
	/**
	 * @var string
	 */
	public $FullName;
	/**
	 * @var string
	 */
	public $Name;

	/**
	 * @param mixed $obj
	 * 
	 * @return void
	 */
	public function __construct ($obj) {
		#src/system/TypeCS.hx:8: characters 3-56
		$this->FullName = \Type::getClassName(\Type::getClass($obj));
		#src/system/TypeCS.hx:10: characters 3-42
		$i = HxString::lastIndexOf($this->FullName, ".");
		#src/system/TypeCS.hx:11: characters 3-68
		$this->Name = ($i === -1 ? $this->FullName : \mb_substr($this->FullName, $i + 1, null));
	}
}

Boot::registerClass(TypeCS::class, 'system.TypeCS');
